### PR TITLE
Feature/aran geometry

### PR DESCRIPTION
**Pull request by AranBorkum**
Rearanged some of the file structure for biulding the geometry.
Added some macros in the `root/` directory for checking the geometry.
Includes more detailed constructing of the 10kt geometry for DUNE simulations

### CODE REVIEW

**Comment by tomjunk** [comment]
Hi Aran,

Before approving this, I did skim through some of the code and I had some questions.  The cathode thickness in Cryostat.py looks like it's 160 microns, but in ProtoDUNE-SP, it was a 3mm-thick piece of FR-4.  There are also 1-inch-high frames holding the cathode up, but they were not simulated in the ProtoDUNE-SP geometry.  Turns out LArSoft didn't like non-rectangular prism active volumes.  We can see those frame pieces in the data -- they don't make hits.  There are probably non-geometry solutions to this, such as deleting energy deposits made inside the cathode frames.

Another thing that raises a question is the handling of the gaps between the APAs in Cryostat.py.  
                    xpos += x_i*APAToAPA[0]
                    ypos += y_i*(APAToAPA[1] + self.APAGap_y)
                    zpos += z_i*(APAToAPA[2] + self.APAGap_z)

where APAToAPA is the dimension of a TPC.  Are the gaps not part of the TPC volume?  We used to have an issue with the 35t geometry where the argon volume directly over the gaps was not active.  But it really is, and charge drifts in towards the nearest collection-plane wire, though some mis-collects on the grid and induction-plane wires.  We'd also be missing photons from tracks over the gaps if they are not active.  Maybe they are active, I cannot tell by a cursory glance at the code.

Another feature of the gaps between the APAs is that every third gap will be bigger than the other two.  This has to do with three APAs sharing a support rail, and the next three on a different support.

**Comment by AranBorkum** [comment]
Hi Tom, 

Thank you very much for looking over this. Hopefully I can address some of the points that you've raised.

The Cathodes:
When we were making the geometry we were trying to take as many measurements from the existing Perl scripts. For the CPA we used the measurements from `generate_dune10kt_v4.pl` lines 248-250. The thickness can be changed to what is used in protoDUNE easily so I'll make that adjustment. Regarding the frames holding up the cathodes, I didn't see them, but I'll look for some design parameters and add them in.

APA positioning:
These incriments were also taken from the Perl scripts for the 1x2x6. Similarly the size of the volTPCActives was taken from those build parameters. In an update I can expand the size of them so that the spacing between the APAs is within an active area. I'll also try and find the design parameters for the APA spacing so that every third gap is as it should be. 

Thanks again for looking over this, I'll make some changes and get back to you

**Comment by tomjunk** [comment]
Hi Aran,

Thanks much!  The frames may be a problem -- Martin had problems with an active volume that was
the complement of the cathode-with-frame structure.  I think larsoft's geometry wants rectangular prisms
as active volumes, and to have bars cut out of it caused some complication. Best check with Martin on that one.
Or the simulations group.  Ajib Paudel has been making lots of plots in the data showing that hits do not get
made when tracks pass through the frames, as expected, though this is not simulated.  We could simulate it
in an ad hoc way just by removing sim energy deposits.

--
Thomas R. Junk
Senior Scientist

Neutrino Division
Fermi National Accelerator Laboratory
630 840 3072 office
www.fnal.gov<http://www.fnal.gov/>
trj@fnal.gov<mailto:trj@fnal.gov>

**Comment by tomjunk** [comment]
Hi Aran,

Tom is correct. I do have a better model of CPA including the framing.
It is missing the field shaping aluminum profiles on the edges. However,
due to overlaps with the sensitive argon volume I had to subtract the
CPA overlaps from the active volume which resulted in a complex shape
that the voxelization didn’t like. Currently, the geometry contains the
correct thickness of the CPA (thickness of the largest area) but the frame
pieces are missing.

Cheers,

Martin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by plasorak** [comment]
For what DAQ (and Aran) is concerned, I think it is probably enough. Would there be anyone to pick this up? The reason why this was started in the first place was to get a reliable neutron capture rate, with realistic external volumes and shielding.

**Comment by tomjunk** [comment]
I am happy to proceed with this -- I don't want to hold up progress even if there are things that can still be improved.  In LArSoft's repositories, we L2 managers approve, and a L1 manager does the merge.  I can push the Merge pull request button and see what happens.

**Comment by tomjunk** [comment]
Okay, merged.

**Comment by plasorak** [comment]
Thanks Tom!

**Pull request merged**
